version: "3.9"
services:
  web:
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    image: writerbackend:v1
    environment:
      - PORT=8020
    env_file:
      - .env
    ports:
      - "8001:8020"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    volumes:
      - staticfiles:/app/static/
      - media:/app/media/

  postgres_db:
    image: postgres
    command: -p 5444
    env_file:
      - .env
    expose:
      - 5444
    ports:
      - "5444:5444"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis_db:
    image: redis
    restart: always
    expose:
      - 6380
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6380

#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./certbot/conf:/etc/letsencrypt  # Map the Certbot configuration
#      - ./certbot/www:/var/www/certbot
#    depends_on:
#      - django
#
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
#    depends_on:
#      - nginx
#    command: certbot renew


volumes:
  staticfiles:
  media:
  #    external: true
  postgres_data:
  redis_data: