# Generated by Django 5.0.3 on 2024-03-21 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_order_writer"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderfile",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_files",
                to="core.order",
            ),
            preserve_default=False,
        ),
    ]
