# Generated by Django 5.0.3 on 2024-03-21 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_orderfile_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="academic_level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="works",
                to="core.academiclevel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="pages",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="order",
            name="paper_format",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="preferred_language_style",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="sources_needed",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="words",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="work_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="works",
                to="core.worktype",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Work",
        ),
    ]
