# Generated by Django 5.0.3 on 2024-03-21 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_order_academic_level_order_pages_order_paper_format_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordermessage",
            options={"ordering": ["created_at"]},
        ),
    ]
