# Generated by Django 5.0.3 on 2024-03-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_is_admin_user_is_client_user_is_writer"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
